version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ecommerce_user:ecommerce_pass@db:5432/ecommerce_data
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: python main.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ecommerce_data
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=ecommerce_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: