name: CI/CD pipeline for Backend Service

on:
    push:
        branches: [main, feature/build-cicd]

env:
    DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}
    DOCKER_TAG: ${{ vars.DOCKER_TAG }}
jobs:
    build-and-push:
        name: Build Backend Service
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and Push Docker Image
              run: |
                  docker build --no-cache -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
                  docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
